### ISSUE TITLE
Instructions for configuring and running

### ISSUE THREAD

**Issue by Pusherman2** [sokenny/trading_bot#1]
Hi there,

Interesting project. Could you include some instructions on how to configure and run it? So how to add keys, running backtest and configuring parameters/running live?

Thank you and kind regards.

**Comment by sokenny** [comment]
Hi. Thank you for your interest in the project. I will work on putting together a clear set of instructions to get the bot up and running.

**Comment by Pusherman2** [comment]
Hi there Sokenny,

Any update on the instructions :)? Would love to test it.

Kind regards.

**Comment by Pusherman2** [comment]
Hey @sokenny,

Thank you for reaching out. No problem, that sounds good! Let me know and I will check it out :) 

Kind regards.
